name: Basic Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Build successful!"

      - name: Test step
        run: echo "Tests passed!"

      - name: Deploy step
        run: echo "Deployment step executed!"
